Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: bind EADDRINUSE null:3000
    at listenOnPrimaryHandle (node:net:1885:18)
    at rr (node:internal/cluster/child:162:12)
    at Worker.<anonymous> (node:internal/cluster/child:112:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:529:35)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2025-06-28T14:16:16: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:17: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:18: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:18: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:19: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:19: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:20: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:20: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:21: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:22: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:23: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:23: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:24: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:24: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:25: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:26: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:26: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:16:27: ❌ Database connection failed: password authentication failed for user "postgres"
2025-06-28T14:17:45: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:47: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:48: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:48: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:49: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:50: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:50: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:51: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:51: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:52: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:52: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:53: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:54: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:55: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:55: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:56: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:56: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:57: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:17:57: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:43: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:44: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:45: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:45: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:46: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:46: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:47: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:47: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:48: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:48: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:49: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:49: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:50: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:51: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:52: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:52: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:53: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T14:18:54: ❌ Database connection failed: password authentication failed for user "domli_user"
2025-06-28T18:38:05: ❌ Query error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:38:05: Get property error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:38:49: ❌ Query error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:38:49: Get property error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:38:54: ❌ Query error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:38:54: Get property error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:39:28: ❌ Query error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:39:28: Get property error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:39:48: ❌ Query error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:39:48: Get property error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:40:54: ❌ Query error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
2025-06-28T18:40:54: Get property error: error: relation "properties" does not exist
    at /Users/leo/Documents/olimp/domli/backend/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async query (file:///Users/leo/Documents/olimp/domli/backend/config/database.js:34:17)
    at async file:///Users/leo/Documents/olimp/domli/backend/routes/properties.js:310:28 {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '197',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
